name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set version
        id: set_version
        run: echo "::set-output name=VERSION::1.0.0"  # Hardcoded version for testing

      - name: Delete remote tag if it exists
        run: |
          git fetch --tags
          git tag -d v${{ steps.set_version.outputs.VERSION }} || true
          git push origin :refs/tags/v${{ steps.set_version.outputs.VERSION }} || true

      - name: Create Tag
        id: create_tag
        run: |
          git tag v${{ steps.set_version.outputs.VERSION }}
          git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/pizoneuser/Demo.git v${{ steps.set_version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Set execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Build Project
        run: ./gradlew assembleRelease  # Build the project to generate APKs

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.set_version.outputs.VERSION }}
          name: Release v${{ steps.set_version.outputs.VERSION }}
          body: |
            Initial release for version v${{ steps.set_version.outputs.VERSION }}.
          files: |
            app/build/outputs/apk/release/app-release.apk  # Adjust path if needed
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
