name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set version
        id: set_version
        run: echo "::set-output name=VERSION::1.0.0"  # Hardcoded version for testing

      - name: Create Tag
        id: create_tag
        run: |
          git tag v${{ steps.set_version.outputs.VERSION }}
          git push origin v${{ steps.set_version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Build Project
        run: ./gradlew assembleRelease  # Build the project to generate APKs

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.set_version.outputs.VERSION }}
          name: Release v${{ steps.set_version.outputs.VERSION }}
          body: |
            Initial release for version v${{ steps.set_version.outputs.VERSION }}.
          files: |
            app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
